env: "local"
HTTPServer:
  Host: "localhost"
  Port: 8080
  Timeout: 4s
  IdleTimeout: 60s
DBServer:
  Host: "localhost"
  Port: 5432
  Username: "G1nxx"
  DBName: "music-stream-service"
  SSLMode: "disable"
  Password: "password1"
S3Config:
  Region: "us-east-1"
  AccessKeyID: "minioadmin"
  SecretAccessKey: "minioadmin"
  Endpoint: "http://localhost:9000"
  DisableSSL: true
  ForcePathStyle: true
RedisConfig:
  Addr: "localhost:6379"
  Password: "password2"
  User: "G1nxx"
  DB: 0
  MaxRetries: 5
  DialTimeout: 10s
  Timeout: 5s